# Generated by Django 3.2.3 on 2021-05-24 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lmdb', '0002_auto_20210524_1450'),
    ]

    operations = [
        migrations.AddField(
            model_name='comentario',
            name='comentário',
            field=models.CharField(default='Sem comentário', max_length=500),
        ),
    ]
