# Generated by Django 3.2.3 on 2021-05-24 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lmdb', '0003_comentario_comentário'),
    ]

    operations = [
        migrations.CreateModel(
            name='Streaming',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=30)),
                ('link', models.CharField(max_length=30)),
                ('imagem', models.ImageField(upload_to='plataformas_streaming')),
            ],
        ),
    ]
