# Generated by Django 3.2.3 on 2021-05-24 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lmdb', '0004_streaming'),
    ]

    operations = [
        migrations.AlterField(
            model_name='streaming',
            name='imagem',
            field=models.ImageField(upload_to='images/'),
        ),
    ]
