# Generated by Django 3.2.3 on 2021-05-25 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lmdb', '0005_alter_streaming_imagem'),
    ]

    operations = [
        migrations.AddField(
            model_name='streaming',
            name='tipo',
            field=models.CharField(default='Generalista', max_length=30),
        ),
    ]
